spring.application.name: testDataRest

server:
  port: ${SERVER_PORT}

spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_EXTERNAL_PORT}/${DB_NAME}

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true


  data:
    jdbc:
      dialect: postgresql
    rest:
      base-path: /api
      detection-strategy: annotated

